export const API_URL = "https://jsonplaceholder.typicode.com";

export const origins: string[] = [
  "New York",
  "Miami",
  "Chicago",
  "Dallas",
  "Houston",
  "Atlanta",
  "Phoenix",
  "Seattle",
  "Denver",
  "Boston",
];

export const destinations: string[] = [
  "San Francisco",
  "Los Angeles",
  "San Diego",
  "Las Vegas",
  "Charlotte",
  "Portland",
  "Nashville",
  "Austin",
  "Orlando",
  "Philadelphia",
];

export const statuses = [
  "pending",
  "in-transit",
  "delivered",
  "cancelled",
] as const;

export const statusOptions = [
  { label: "Pending", value: "pending" },
  { label: "In Transit", value: "in-transit" },
  { label: "Delivered", value: "delivered" },
  { label: "Cancelled", value: "cancelled" },
];

export const imageUrls = [
  "https://i.postimg.cc/d0GQn55W/apple-black-case.jpg",
  "https://i.postimg.cc/4y2Xnq33/apple-ipad.jpg",
  "https://i.postimg.cc/9Q6FG6YR/apple-iphone.jpg",
  "https://i.postimg.cc/fLKzQJnm/apple-red-cases.jpg",
  "https://i.postimg.cc/0Qxk4739/avocado-plush.jpg",
  "https://i.postimg.cc/tCmggZ1z/bear-plush.jpg",
  "https://i.postimg.cc/BQv6scv6/black-bike-helmet.jpg",
  "https://i.postimg.cc/dQ61zSwp/black-nike-sport-shoes.jpg",
  "https://i.postimg.cc/3x4x08mQ/black-notebook.jpg",
  "https://i.postimg.cc/RFQFCgf3/black-shirt.jpg",
  "https://i.postimg.cc/cCFLw6F0/black-sony-headphones.jpg",
  "https://i.postimg.cc/C5hKRbHc/boss-perfume.jpg",
  "https://i.postimg.cc/jjf2mxS4/brown-couch.jpg",
  "https://i.postimg.cc/Sx3jg2kK/cdx-headphones.jpg",
  "https://i.postimg.cc/JzGG3cwg/chanel-beauty-kit.jpg",
  "https://i.postimg.cc/v8tgGZLP/coco-perfume-dark.jpg",
  "https://i.postimg.cc/xCKkJfr1/curology-body-cream.jpg",
  "https://i.postimg.cc/d1MkV7xf/custom-sport-shoes-colorfull.jpg",
  "https://i.postimg.cc/qq4N2P0X/cute-body-cream.jpg",
  "https://i.postimg.cc/prJn72k6/cute-notebook.jpg",
  "https://i.postimg.cc/6pm4FbLt/cyan-shoe.jpg",
  "https://i.postimg.cc/gkGhhZ2F/dark-watch.jpg",
  "https://i.postimg.cc/Ghzyxm4B/elegant-notebook.jpg",
  "https://i.postimg.cc/MGffw0dR/elegant-watch.jpg",
  "https://i.postimg.cc/L5p1NqkP/erbology-body-cream.jpg",
  "https://i.postimg.cc/Pq0ZvVP2/four-shirts-pack.jpg",
  "https://i.postimg.cc/W1b0BJB6/ghost-watch.jpg",
  "https://i.postimg.cc/1z8wt158/golden-sport-shoes.jpg",
  "https://i.postimg.cc/hPnL0YMY/green-sofa.jpg",
  "https://i.postimg.cc/4xLpsxZC/grey-sofa.jpg",
  "https://i.postimg.cc/59L5LJ5v/lama-plush.jpg",
  "https://i.postimg.cc/GtysLLXK/lipstick.jpg",
  "https://i.postimg.cc/zfQwSXPw/lumix-camera.jpg",
  "https://i.postimg.cc/SR6WhLQV/men-elegant-watch.jpg",
  "https://i.postimg.cc/8cQh9XGj/modern-glasses.jpg",
  "https://i.postimg.cc/DZbrCkt9/modern-outfit.jpg",
  "https://i.postimg.cc/BQ5g93Xs/modern-sofa.jpg",
  "https://i.postimg.cc/t42NJz3M/modern-sport-shoes.jpg",
  "https://i.postimg.cc/65x0mq6Y/nike-red-shoes.jpg",
  "https://i.postimg.cc/J0ZQhVxN/nora-body-oil.jpg",
  "https://i.postimg.cc/nzsk6QQw/pink-notebook.jpg",
  "https://i.postimg.cc/0QLfx2Y5/pink-sport-shoes.jpg",
  "https://i.postimg.cc/T2D00gxK/purple-shirt.jpg",
  "https://i.postimg.cc/jj3cghC7/ray-ban-glasses.jpg",
  "https://i.postimg.cc/mgw8M4sV/red-handbag.jpg",
  "https://i.postimg.cc/R0ZGLYCm/rolex-watch.jpg",
  "https://i.postimg.cc/521s60Z6/simple-notebook.jpg",
  "https://i.postimg.cc/rF5hVWZB/six-shirts-pack.jpg",
  "https://i.postimg.cc/447L0j6N/slim-watch.jpg",
  "https://i.postimg.cc/Y9VX9xHH/three-shirts-pack.jpg",
  "https://i.postimg.cc/1XqvNNmN/versage-perfume.jpg",
  "https://i.postimg.cc/XJXH4ztL/vintage-camera.jpg",
  "https://i.postimg.cc/FHgnZcjy/white-hoodie.jpg",
  "https://i.postimg.cc/Pf9crdXw/white-ps5.jpg",
  "https://i.postimg.cc/Df8HTSTh/white-sport-shoes.jpg",
  "https://i.postimg.cc/wTNr1nMb/women-elegant-watch.jpg",
];
